export const SWITCH = 'SWITCH';
export const MOVE_COMPONENT = 'MOVE_COMPONENT';
export const SELECT_COMPONENT = 'SELECT_COMPONENT';
export const MERGE_SELECTED_COMPONENTS = 'MERGE_SELECTED_COMPONENTS';

